### ISSUE TITLE
outputs 49 character hash sometimes

### ISSUE THREAD

**Issue by joehand** [juliangruber/dat-encoding#7]
Can't regularly reproduce but sometimes I am getting 49 character hashes. 

Example:

`8smfyktjyipyx0dm5qb1htx5zuiycc1ay341yy1acjpyfdx4o`

**Comment by juliangruber** [comment]
that's weird, i thought the base-x module would 0-pad by default. i'll look into it

**Comment by juliangruber** [comment]
is this a real problem? or just something we should document

**Comment by joehand** [comment]
Ya, we should always have the same length hashes.

**Comment by juliangruber** [comment]
just so i get the complete picture, can you tell me why?

**Comment by joehand** [comment]
Sure =). Mostly I think it will be easier for documentation/users. If we say the links in dat are 50 characters, we'd always have to qualify saying they are sometimes 49 characters. That could be really confusing. 

But it'll also be easier to check/test if hashes are consistent length. I am just using a regex to check for 50 alphanumeric characters right now. We could make it 49 or 50 but if a user incorrectly copies a 50 character one and to be 49 characters, we can't throw a helpful error message.

And if we end up using this hash across dat.haus, dat.land, desktop, and CLI I think it will introduce similar errors.
