### ISSUE TITLE
encode should return .toString('hex')

### ISSUE THREAD

**Issue by karissa** [juliangruber/dat-encoding#9]
hey

I like the simplicity of this module and want to be able to encode/decode dat links to check their validity etc. But it'd be nice if the `encoding.encode` function returned the same thing that hyperdrive does. If we want to use the smaller hashes, can we put that part into a different function, perhaps?

**Comment by juliangruber** [comment]
is this strictly necessary? as long as we're always using buffers in the backend and only send encoded links to the user, it should all be fine

**Comment by juliangruber** [comment]
this is only doing hex now :)
